[WIP] Integrating DAG tool
HEP-FCC/fcc-edm pull request #27
Opened 2016-10-25 16:08 UTC by jlingema

This provides a class that can build Alice's DAG from an `fcc::MCParticleCollection`. WIP because I need to update the fcc-spi init script to pick up the DAG installation (will be done with the rest we need to change for the upcoming release)

2017-03-03 10:21 UTC, jlingema commented
Ready to merge from my point of view.

2017-03-20 14:20 UTC, vvolkl requested changes

2017-03-20 14:20 UTC, vvolkl commented on utilities/ParticleUtils.cc
>  // datamodel
Could you remove the commented code in this file?

2017-03-20 14:20 UTC, vvolkl commented on examples/graph.cc
> +  * example on how to use it in the context of the fcc-edm, have a look at the read example in fcc-physics.
I may have missed something, but the read example in fcc-physics doesn't use graphs?

2017-03-20 14:20 UTC, vvolkl commented on utilities/ParticleGraph.cc
> +    if (startID.collectionID != -2) {
Could you add a comment what -2 is in this context?

2017-03-20 14:24 UTC, vvolkl commented
Thanks, looks great! Maybe you can remove the commented code in the file, and I noted the few places where things weren't totally clear to me.

2017-03-20 16:51 UTC, jlingema commented
Hi Valentin,
Thanks for the feedback. Your comments are addressed in the last commits. Instead of referring to fcc-physics for an example, I added a simple test (actually before we were missing any test of that class) here that uses the `ParticleGraph` and refer to that. It shows at least how the basic interaction works. The actual implementation in FCCSW will also be an example for more refined usage and is referred to (will create a PR there, once this is accepted and installed).

Cheers,
Joschka

2017-03-20 16:57 UTC, vvolkl approved these changes

2017-03-20 16:59 UTC, merged